[package]
authors = ["Dylan Frankland <dylan@frankland.io>"]
edition = "2018"
name = "domshot"
version = "0.1.0"
[dependencies]
image = "0.21.1"
tokio = "0.1.20"

[dependencies.azul]
git = "https://github.com/maps4print/azul"
